language: php

php:
  - 5.4

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxss1 
    - bin/travis_build_before

script:
    - phpunit -c app
    - php -d memory_limit=2048M bin/behat @MyProjectWebsiteBundle --verbose

notifications:
  email:
    - travis@kunstmaan.be
